"use client"
import { useCallback, useEffect, useState } from "react"
import { addMonths, format, startOfMonth, subMonths } from "date-fns"
import { CalendarIcon, ChevronLeft, ChevronRight, Loader2, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { TabAnalysis } from "./tab-analysis"
import { TabBaseline } from "./tab-baseline"
import { TabBoilerMix } from "./tab-boiler-mix"
import { TabDashboard } from "./tab-dashboard"
import { BaselineModel, BoilerProcessMix, DailyEntry, MonthlyHistorical, SeuMaster, SeuSummary, WoodSavingStatus } from "./types"
const editorRoles=['admin','hse','hse_admin']
export function ISO50001Content({ userRole }: {userRole:string;userEmail:string}) {
 const [currentMonth,setCurrentMonth]=useState(startOfMonth(new Date())),[isLoading,setIsLoading]=useState(true),[blLoading,setBlLoading]=useState(true)
 const [entries,setEntries]=useState<DailyEntry[]>([]),[summaries,setSummaries]=useState<SeuSummary[]>([]),[dashboardHistorical,setDashboardHistorical]=useState<MonthlyHistorical[]>([]),[boilerMix,setBoilerMix]=useState<BoilerProcessMix|null>(null),[woodSavingStatus,setWoodSavingStatus]=useState<WoodSavingStatus>('missing-data')
 const [seus,setSeus]=useState<SeuMaster[]>([]),[historical,setHistorical]=useState<MonthlyHistorical[]>([]),[baselines,setBaselines]=useState<BaselineModel[]>([])
 const monthStr=format(currentMonth,'yyyy-MM'),isEditor=editorRoles.includes(userRole.toLowerCase())
 const fetchDashboard=useCallback(async()=>{setIsLoading(true);try{const r=await fetch(`/api/iso50001/dashboard?month=${monthStr}`);const j=await r.json();if(!r.ok) throw new Error(j.error ?? 'Unable to load dashboard');setEntries(j.entries||[]);setSummaries(j.summaries||[]);setDashboardHistorical(j.historicalData||[]);setBoilerMix(j.boilerMix||null);setWoodSavingStatus(j.woodSavingStatus||'missing-data')}finally{setIsLoading(false)}},[monthStr])
 const fetchBaseline=useCallback(async()=>{setBlLoading(true);try{const r=await fetch('/api/iso50001/baseline');const j=await r.json();if(!r.ok) throw new Error(j.error ?? 'Unable to load baseline data');setSeus(j.seus||[]);setHistorical(j.historical||[]);setBaselines(j.baselines||[])}finally{setBlLoading(false)}},[])
 const refresh=useCallback(()=>{void fetchDashboard();void fetchBaseline()},[fetchDashboard,fetchBaseline]);useEffect(()=>{void fetchDashboard()},[fetchDashboard]);useEffect(()=>{void fetchBaseline()},[fetchBaseline])
 return <div className="flex-1 space-y-4 md:space-y-5 w-full"><div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3"><div><h2 className="text-xl font-bold tracking-tight flex items-center gap-2 text-primary"><ShieldCheck className="h-5 w-5"/>Energy Management System (ISO 50001)</h2><p className="text-muted-foreground text-xs mt-0.5">Performance monitoring and energy baseline tracking.</p></div><div className="flex items-center gap-1.5 bg-background border rounded-md p-1 shadow-sm"><Button variant="ghost" size="icon" onClick={()=>setCurrentMonth(m=>subMonths(m,1))}><ChevronLeft/></Button><div className="min-w-[130px] text-sm font-semibold"><CalendarIcon className="inline mr-1.5 h-3.5 w-3.5"/>{format(currentMonth,'MM/yyyy')}</div><Button variant="ghost" size="icon" onClick={()=>setCurrentMonth(m=>addMonths(m,1))} disabled={currentMonth>=startOfMonth(new Date())}><ChevronRight/></Button></div></div><Tabs defaultValue="dashboard"><TabsList><TabsTrigger value="dashboard">Dashboard</TabsTrigger><TabsTrigger value="seu">Phân Tích</TabsTrigger>{isEditor&&<><TabsTrigger value="boiler-mix">Mix hấp & Borma</TabsTrigger><TabsTrigger value="baseline">Baseline</TabsTrigger></>}</TabsList><TabsContent value="dashboard">{isLoading?<div className="flex justify-center h-48"><Loader2 className="animate-spin"/></div>:<TabDashboard entries={entries} summaries={summaries} historical={dashboardHistorical} currentMonth={currentMonth} boilerMix={boilerMix} woodSavingStatus={woodSavingStatus}/>}</TabsContent><TabsContent value="seu">{blLoading?<Loader2 className="animate-spin"/>:<TabAnalysis summaries={summaries} historical={historical} currentMonth={currentMonth}/>}</TabsContent>{isEditor&&<TabsContent value="boiler-mix"><TabBoilerMix currentMonth={currentMonth} mix={boilerMix} onSaved={refresh}/></TabsContent>}{isEditor&&<TabsContent value="baseline">{blLoading?<Loader2 className="animate-spin"/>:<TabBaseline seus={seus} historical={historical} baselines={baselines} onRefresh={refresh}/>}</TabsContent>}</Tabs></div>
}
