"use client"

import { format } from "date-fns"
import { vi } from "date-fns/locale"
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { AlertTriangle, Droplets, Flame, TrendingDown, TrendingUp, Zap } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { BoilerProcessMix, DailyEntry, MonthlyHistorical, SeuSummary, WaterEnpiReference, WoodSavingStatus, deviationBg, deviationColor, fmtNum } from "./types"

interface Props {
  entries: DailyEntry[]; summaries: SeuSummary[]; historical: MonthlyHistorical[]; currentMonth: Date
  boilerMix: BoilerProcessMix | null; woodSavingStatus: WoodSavingStatus; waterEnpiReference: WaterEnpiReference | null
}

export function TabDashboard({ entries, summaries, historical, currentMonth, boilerMix, woodSavingStatus, waterEnpiReference }: Props) {
  const electricity = summaries.find(s => s.energy_type === 'electricity')
  const wood = summaries.find(s => s.energy_type === 'wood')
  const water = summaries.find(s => s.energy_type === 'water')
  const electricityChart = entries.filter(e => e.seu?.energy_type === 'electricity').map(e => ({ date: format(new Date(e.entry_date), 'dd/MM'), actual: e.actual_energy, expected: e.expected_energy }))
  const missingBaseline = summaries.some(s => s.energy_type !== 'wood' && !s.has_baseline)

  return <div className="space-y-4">
    <p className="text-sm text-muted-foreground">Tháng: <span className="font-semibold text-foreground">{format(currentMonth, 'MMMM yyyy', { locale: vi })}</span></p>

    <Card className="border-2 border-amber-400 bg-amber-50 shadow-sm">
      <CardHeader className="pb-2"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-700"/><Badge className="bg-amber-700">ĐANG TÍNH LẠI ĐƯỜNG CƠ SỞ CỦI</Badge></div>
        <CardTitle className="text-lg text-amber-950">Chưa công bố mức tiết kiệm củi chính thức</CardTitle>
        <CardDescription className="text-amber-900">Cơ cấu sản xuất đã thay đổi và một lò hơi dùng chung đang cấp hơi cho cả công đoạn hấp và Borma. Đường cơ sở cũ không còn đủ tính so sánh; chỉ công bố tiết kiệm sau khi đường cơ sở đa biến mới được phê duyệt.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3"><div className="rounded-lg border border-amber-200 bg-white/70 p-3 text-sm"><strong>Khái niệm công thức đang xây dựng:</strong> Củi dự kiến = f(RCN tự hấp, RCN chẻ sẵn nhận vào, đầu vào Borma, giờ chạy Borma, độ ẩm vào/ra)</div>
        <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">
          <MixMetric label="RCN tự hấp" value={boilerMix?.self_steamed_rcn_kg}/><MixMetric label="RCN chẻ sẵn nhận vào" value={boilerMix?.received_precut_rcn_kg}/><MixMetric label="Đầu vào Borma" value={boilerMix?.borma_input_kg}/><MixMetric label="Giờ chạy Borma" value={boilerMix?.borma_runtime_hours} unit="giờ"/><MixMetric label="Độ ẩm đầu vào" value={boilerMix?.moisture_in_pct} unit="%"/><MixMetric label="Độ ẩm đầu ra" value={boilerMix?.moisture_out_pct} unit="%"/>
        </div><p className="text-xs text-amber-800">Trạng thái dữ liệu: {woodSavingStatus === 'missing-data' ? 'còn thiếu đầu vào theo dõi.' : 'đang theo dõi, chưa đủ điều kiện so sánh chính thức.'} Lượng nhận chẻ sẵn và đầu vào Borma được theo dõi độc lập.</p>
      </CardContent>
    </Card>

    {missingBaseline && <div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><AlertTriangle className="h-4 w-4 shrink-0"/>Một hoặc nhiều SEU (không gồm củi đang tính lại) chưa có đường cơ sở được kích hoạt.</div>}

    <Card><CardHeader><CardTitle className="text-sm">Tổng hợp kết quả SEU trong tháng</CardTitle><CardDescription>Thực tế và so sánh với đường cơ sở; riêng củi tạm ngừng so sánh trong giai đoạn tính lại.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">SEU</th><th className="px-4 py-3 text-right">Thực tế</th><th className="px-4 py-3 text-right">Dự kiến</th><th className="px-4 py-3 text-right">Đánh giá</th></tr></thead><tbody className="divide-y">{summaries.map(s => <SummaryRow key={s.seu_id} summary={s}/>)}</tbody></table></div></CardContent></Card>

    <div className="grid gap-3 md:grid-cols-3"><Kpi icon={<Zap className="h-4 w-4"/>} label="Điện thực tế" value={electricity?.total_actual} unit="kWh"/><Kpi icon={<Flame className="h-4 w-4"/>} label="Củi thực tế" value={wood?.total_actual} unit="kg"/><Kpi icon={<Droplets className="h-4 w-4"/>} label="Nước thực tế" value={water?.total_actual} unit="m³"/></div>

    <div className="grid gap-3 md:grid-cols-3"><DeviationCard label="Lệch chuẩn điện" pct={electricity?.monthly_deviation_pct}/><DeviationCard label="Lệch chuẩn nước" pct={water?.monthly_deviation_pct}/><div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-xs text-amber-800">Lệch chuẩn củi</p><p className="mt-1 text-sm font-semibold text-amber-900">Đang tính lại đường cơ sở</p></div></div>
    <div className="grid gap-3 md:grid-cols-2"><EnpiCard title="EnPI điện" unit="kWh / kg sản lượng" actual={electricity?.monthly_enpi_actual} baseline={electricity?.monthly_enpi_baseline}/><WaterEnpiCard current={water?.monthly_enpi_actual} reference={waterEnpiReference}/></div>

    <Card><CardHeader><CardTitle className="text-sm">Lịch sử năng lượng gần đây</CardTitle><CardDescription>Dữ liệu tổng hợp theo tháng. Các dòng củi không có giá trị dự kiến sẽ không hiển thị kết luận tiết kiệm.</CardDescription></CardHeader><CardContent className="p-0"><div className="max-h-[500px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">Tháng</th><th className="px-4 py-3 text-left">SEU</th><th className="px-4 py-3 text-right">Sản lượng</th><th className="px-4 py-3 text-right">Thực tế</th><th className="px-4 py-3 text-right">Dự kiến</th><th className="px-4 py-3 text-right">Chênh lệch</th></tr></thead><tbody className="divide-y">{historical.slice(0,120).map(row => <HistoryRow key={row.id} row={row} summary={summaries.find(s=>s.seu_id===row.seu_id)}/>)}</tbody></table></div></CardContent></Card>

    {electricityChart.length > 0 && <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Zap className="h-4 w-4 text-blue-600"/>Điện: thực tế và đường cơ sở (kWh/ngày)</CardTitle></CardHeader><CardContent className="h-[280px]"><ActualChart data={electricityChart}/></CardContent></Card>}
    <Card className="border-orange-200 bg-orange-50/40"><CardContent className="py-6"><div className="flex gap-3"><Flame className="h-5 w-5 text-orange-600"/><div><p className="font-semibold">Biểu đồ so sánh củi tạm thời không hiển thị</p><p className="mt-1 text-sm text-muted-foreground">Không có giá trị củi dự kiến hợp lệ trong thời gian tính lại đường cơ sở. Dữ liệu củi thực tế vẫn được ghi nhận, nhưng không được diễn giải là tiết kiệm hoặc vượt chuẩn.</p></div></div></CardContent></Card>
  </div>
}

function SummaryRow({summary:s}:{summary:SeuSummary}) { const wood=s.energy_type==='wood', noData=s.days===0, pct=s.monthly_deviation_pct; return <tr><td className="px-4 py-3 font-medium">{s.seu_name}</td><td className="px-4 py-3 text-right font-mono">{noData?'Chưa có dữ liệu':`${fmtNum(s.total_actual)} ${s.unit}`}</td><td className="px-4 py-3 text-right font-mono">{wood?'Đang tính lại':(!s.has_baseline?'Chưa có đường cơ sở':noData?'—':`${fmtNum(s.total_expected)} ${s.unit}`)}</td><td className="px-4 py-3 text-right">{wood?<span className="text-xs font-medium text-amber-700">Chưa kết luận tiết kiệm</span>:pct==null?'—':<Badge className={`${deviationBg(pct)} ${deviationColor(pct)}`} variant="outline">{pct<=0?<TrendingDown className="mr-1 inline h-3 w-3"/>:<TrendingUp className="mr-1 inline h-3 w-3"/>}{pct>0?'+':''}{fmtNum(pct)}%</Badge>}</td></tr> }
function MixMetric({label,value,unit='kg'}:{label:string;value?:number|null;unit?:string}) { const shown=value==null?'Chưa nhập':unit==='kg'?`${fmtNum(value/1000)} tấn`:`${fmtNum(value)} ${unit}`; return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{shown}</p></div> }
function Kpi({icon,label,value,unit}:{icon:React.ReactNode;label:string;value?:number|null;unit:string}) { return <div className="rounded-xl border bg-slate-50 p-3"><div className="mb-1 flex items-center gap-1.5 text-xs text-muted-foreground">{icon}{label} (MTD)</div><p className="text-xl font-black">{fmtNum(value)} <span className="text-xs">{unit}</span></p></div> }
function DeviationCard({label,pct}:{label:string;pct?:number|null}) { const saving=pct!=null&&pct<=0; return <div className={`rounded-xl border p-3 ${deviationBg(pct)}`}><p className="text-xs text-muted-foreground">{label}</p>{pct==null?<p className="mt-1 text-sm text-muted-foreground">Chưa có đường cơ sở</p>:<p className={`mt-1 text-xl font-black ${deviationColor(pct)}`}>{saving?<TrendingDown className="mr-1 inline h-4 w-4"/>:<TrendingUp className="mr-1 inline h-4 w-4"/>}{pct>0?'+':''}{fmtNum(pct)}%</p>}</div> }
function EnpiCard({title,unit,actual,baseline}:{title:string;unit:string;actual?:number|null;baseline?:number|null}) { const comparison=actual!=null&&baseline!=null&&baseline>0?((actual-baseline)/baseline)*100:null; const better=comparison!=null&&comparison<0; return <Card><CardHeader className="pb-1"><CardTitle className="text-sm">{title}</CardTitle><CardDescription>{unit}</CardDescription></CardHeader><CardContent><div className="flex items-end justify-between"><div><p className="text-2xl font-black">{fmtNum(actual,6)}</p><p className="text-xs text-muted-foreground">Thực tế</p></div><div className="text-right"><p className="font-semibold">{fmtNum(baseline,6)}</p><p className="text-xs text-muted-foreground">Đường cơ sở</p></div></div>{comparison!=null&&<Badge variant="outline" className={`mt-2 ${better?'border-emerald-300 bg-emerald-50 text-emerald-700':'border-red-300 bg-red-50 text-red-700'}`}>{better?'Tốt hơn':'Kém hơn'} {comparison>0?'+':''}{fmtNum(comparison)}%</Badge>}</CardContent></Card> }function WaterEnpiCard({current,reference}:{current?:number|null;reference:WaterEnpiReference|null}) { const c=reference?.comparison; const good=c?.status==='better'; return <Card className="border-teal-200"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Droplets className="h-4 w-4 text-teal-600"/>EnPI nước — tháng đã chọn so với tham chiếu năm 2025</CardTitle><CardDescription>Chỉ số thấp hơn là tốt hơn. Tham chiếu gia quyền = tổng nước (m³) / tổng RCN hấp được (kg), không phải trung bình các tỷ lệ tháng.</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><Metric label="Tháng đã chọn" value={current}/><Metric label="Tham chiếu gia quyền 2025" value={reference?.value}/><div><p className="text-xs text-muted-foreground">So với tham chiếu</p>{c?<><p className={`text-2xl font-black ${good?'text-emerald-700':c.status==='worse'?'text-red-700':'text-slate-700'}`}>{c.deltaPct>0?'+':''}{fmtNum(c.deltaPct)}%</p><p className="text-xs font-medium">{good?'Tốt hơn (dùng ít nước hơn)':c.status==='worse'?'Kém hơn (dùng nhiều nước hơn)':'Tương đương'}</p></>:<p className="font-semibold text-muted-foreground">Chưa đủ dữ liệu</p>}</div></div><p className="mt-3 text-xs text-muted-foreground">Độ phủ tham chiếu: <strong>{reference?.coverageCount ?? 0} tháng hợp lệ</strong> trong năm 2025.</p></CardContent></Card> }
function Metric({label,value}:{label:string;value?:number|null}) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-black">{fmtNum(value,6)}</p><p className="text-xs text-muted-foreground">m³ / kg RCN hấp được</p></div> }
function HistoryRow({row,summary}:{row:MonthlyHistorical;summary?:SeuSummary}) { const expected=row.expected_energy==null?null:Number(row.expected_energy), actual=Number(row.actual_energy)||0, pct=expected&&expected>0?((actual-expected)/expected)*100:null; return <tr><td className="px-4 py-2 font-mono">{format(new Date(row.month_year),'MM/yyyy')}</td><td className="px-4 py-2">{summary?.seu_name||row.seu?.name}</td><td className="px-4 py-2 text-right font-mono">{fmtNum(Number(row.rcn_hap_duoc_kg)||0)} kg</td><td className="px-4 py-2 text-right font-mono">{fmtNum(actual)} {summary?.unit||row.seu?.unit}</td><td className="px-4 py-2 text-right font-mono">{expected==null?'Không so sánh':fmtNum(expected)}</td><td className="px-4 py-2 text-right">{pct==null?'—':`${pct>0?'+':''}${fmtNum(pct)}%`}</td></tr> }
function ActualChart({data}:{data:{date:string;actual:number;expected?:number|null}[]}) { return <ResponsiveContainer width="100%" height="100%"><ComposedChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(v:any)=>Number(v).toLocaleString('vi-VN')}/><Legend/><Bar dataKey="actual" name="Thực tế" fill="#3B82F6"/><Line dataKey="expected" name="Đường cơ sở" stroke="#6B7280" strokeDasharray="5 3"/></ComposedChart></ResponsiveContainer> }
