-- ISO 50001: monthly Boiler / Borma process-mix tracking.
-- Nullable measurements mean "not recorded"; 0 means a confirmed zero measurement.
-- No historical values are seeded by this migration.
CREATE TABLE IF NOT EXISTS public.iso50001_boiler_process_mix (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 month_year DATE NOT NULL UNIQUE CHECK (date_trunc('month', month_year)::date = month_year),
 self_steamed_rcn_kg NUMERIC CHECK (self_steamed_rcn_kg >= 0),
 received_precut_rcn_kg NUMERIC CHECK (received_precut_rcn_kg >= 0),
 receipt_basis TEXT NOT NULL DEFAULT 'unknown' CHECK (receipt_basis IN ('unknown', 'rcn-equivalent', 'kernel-mass')),
 borma_input_kg NUMERIC CHECK (borma_input_kg >= 0),
 borma_input_basis TEXT NOT NULL DEFAULT 'unknown' CHECK (borma_input_basis IN ('unknown', 'rcn-equivalent', 'kernel-mass')),
 borma_runtime_hours NUMERIC CHECK (borma_runtime_hours >= 0),
 moisture_in_pct NUMERIC CHECK (moisture_in_pct BETWEEN 0 AND 100),
 moisture_out_pct NUMERIC CHECK (moisture_out_pct BETWEEN 0 AND 100),
 data_quality_status TEXT NOT NULL DEFAULT 'draft' CHECK (data_quality_status IN ('draft', 'verified', 'estimated')),
 notes TEXT, created_by UUID REFERENCES auth.users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_by UUID REFERENCES auth.users(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.iso50001_boiler_process_mix ADD COLUMN IF NOT EXISTS receipt_basis TEXT NOT NULL DEFAULT 'unknown' CHECK (receipt_basis IN ('unknown', 'rcn-equivalent', 'kernel-mass'));
ALTER TABLE public.iso50001_boiler_process_mix ADD COLUMN IF NOT EXISTS borma_input_basis TEXT NOT NULL DEFAULT 'unknown' CHECK (borma_input_basis IN ('unknown', 'rcn-equivalent', 'kernel-mass'));
ALTER TABLE public.iso50001_boiler_process_mix ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES auth.users(id);
ALTER TABLE public.iso50001_boiler_process_mix ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "iso_boiler_mix_read_all" ON public.iso50001_boiler_process_mix;
CREATE POLICY "iso_boiler_mix_read_all" ON public.iso50001_boiler_process_mix FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS "iso_boiler_mix_write_admin_hse" ON public.iso50001_boiler_process_mix;
CREATE POLICY "iso_boiler_mix_write_admin_hse" ON public.iso50001_boiler_process_mix FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND lower(role) IN ('admin', 'hse', 'hse_admin'))) WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND lower(role) IN ('admin', 'hse', 'hse_admin')));
CREATE OR REPLACE FUNCTION public.audit_iso_boiler_process_mix() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'INSERT' THEN NEW.created_by := COALESCE(NEW.created_by, auth.uid()); ELSIF TG_OP = 'UPDATE' THEN NEW.created_by := OLD.created_by; NEW.created_at := OLD.created_at; END IF; NEW.updated_at := NOW(); RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS audit_iso_boiler_process_mix ON public.iso50001_boiler_process_mix;
CREATE TRIGGER audit_iso_boiler_process_mix BEFORE INSERT OR UPDATE ON public.iso50001_boiler_process_mix FOR EACH ROW EXECUTE FUNCTION public.audit_iso_boiler_process_mix();
